### ISSUE TITLE
`react-konva-utils` fails to install after updating `konva` to `9.0.0`

### ISSUE THREAD

**Issue by m4rtinpf** [konvajs/react-konva-utils#27]
After updating `konva` to `9.0.0` to fix [this `react-konva` issue](https://github.com/konvajs/react-konva/issues/714#issuecomment-1508902362), `react-konva-utils` fails to install:

```
$ npm i react-konva-utils
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-konva-vitest@0.0.0
npm ERR! Found: konva@9.0.0
npm ERR! node_modules/konva
npm ERR!   konva@"^9.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer konva@"^8.3.5" from react-konva-utils@0.3.2
npm ERR! node_modules/react-konva-utils
npm ERR!   react-konva-utils@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/paul/.npm/_logs/2023-04-14T17_59_46_386Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2023-04-14T17_59_46_386Z-debug-0.log
```

<details>
<summary>Log file</summary>

```
0 verbose cli /home/paul/.nvm/versions/node/v18.16.0/bin/node /home/paul/.nvm/versions/node/v18.16.0/bin/npm
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/paul/.nvm/versions/node/v18.16.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/paul/work/react-konva-vitest/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/paul/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/paul/.nvm/versions/node/v18.16.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm i react-konva-utils
21 verbose argv "i" "react-konva-utils"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/paul/.npm/_logs/2023-04-14T17_59_46_386Z-
26 verbose logfile /home/paul/.npm/_logs/2023-04-14T17_59_46_386Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 10ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 114ms
35 timing idealTree:userRequests Completed in 1ms
36 silly idealTree buildDeps
37 silly fetch manifest react-konva-utils@*
38 timing arborist:ctor Completed in 0ms
39 http fetch GET 200 https://registry.npmjs.org/react-konva-utils 1196ms (cache revalidated)
40 silly fetch manifest konva@^9.0.0
41 http fetch GET 200 https://registry.npmjs.org/konva 977ms (cache revalidated)
42 silly fetch manifest konva@^8.3.5
43 timing idealTree Completed in 2304ms
44 timing command:i Completed in 2310ms
45 verbose stack Error: unable to resolve dependency tree
45 verbose stack     at [failPeerConflict] (/home/paul/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1381:25)
45 verbose stack     at [loadPeerSet] (/home/paul/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1347:34)
45 verbose stack     at async [buildDepStep] (/home/paul/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
45 verbose stack     at async Arborist.buildIdealTree (/home/paul/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
45 verbose stack     at async Promise.all (index 1)
45 verbose stack     at async Arborist.reify (/home/paul/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
45 verbose stack     at async Install.exec (/home/paul/.nvm/versions/node/v18.16.0/lib/node_modules/npm/lib/commands/install.js:146:5)
45 verbose stack     at async module.exports (/home/paul/.nvm/versions/node/v18.16.0/lib/node_modules/npm/lib/cli.js:134:5)
46 verbose cwd /home/paul/work/react-konva-vitest
47 verbose Linux 5.15.0-41-generic
48 verbose node v18.16.0
49 verbose npm  v9.5.1
50 error code ERESOLVE
51 error ERESOLVE unable to resolve dependency tree
52 error
53 error While resolving: [1mreact-konva-vitest[22m@[1m0.0.0[22m
53 error Found: [1mkonva[22m@[1m9.0.0[22m[2m[22m
53 error [2mnode_modules/konva[22m
53 error   [1mkonva[22m@"[1m^9.0.0[22m" from the root project
53 error
53 error Could not resolve dependency:
53 error [35mpeer[39m [1mkonva[22m@"[1m^8.3.5[22m" from [1mreact-konva-utils[22m@[1m0.3.2[22m[2m[22m
53 error [2mnode_modules/react-konva-utils[22m
53 error   [1mreact-konva-utils[22m@"[1m*[22m" from the root project
53 error
53 error Fix the upstream dependency conflict, or retry
53 error this command with --force or --legacy-peer-deps
53 error to accept an incorrect (and potentially broken) dependency resolution.
54 error
54 error
54 error For a full report see:
54 error /home/paul/.npm/_logs/2023-04-14T17_59_46_386Z-eresolve-report.txt
55 verbose exit 1
56 timing npm Completed in 2330ms
57 verbose unfinished npm timer reify 1681495186403
58 verbose unfinished npm timer reify:loadTrees 1681495186405
59 verbose unfinished npm timer idealTree:buildDeps 1681495186522
60 verbose unfinished npm timer idealTree:#root 1681495186523
61 verbose code 1
62 error A complete log of this run can be found in:
62 error     /home/paul/.npm/_logs/2023-04-14T17_59_46_386Z-debug-0.log
```

</details>

<details>
<summary>Report file</summary>

```
'Log files:
/home/paul/.npm/_logs/2023-04-14T17_59_46_386Z-debug-0.log

# npm resolution error report

While resolving: react-konva-vitest@0.0.0
Found: konva@9.0.0
node_modules/konva
  konva@"^9.0.0" from the root project

Could not resolve dependency:
peer konva@"^8.3.5" from react-konva-utils@0.3.2
node_modules/react-konva-utils
  react-konva-utils@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

</details>

Repo to reproduce: https://github.com/m4rtinpf/react-konva-vitest

**Comment by lavrton** [comment]
Try to upgrade to latest. `npm install react-konva-utils@latest`

**Comment by m4rtinpf** [comment]
Same thing:

```
$ npm install react-konva-utils@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-konva@18.2.5
npm ERR! Found: konva@9.0.0
npm ERR! node_modules/konva
npm ERR!   konva@"^9.0.0" from the root project
npm ERR!   peer konva@"^8.3.5 || 9.0.0" from react-konva-utils@1.0.0
npm ERR!   node_modules/react-konva-utils
npm ERR!     react-konva-utils@"1.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer konva@"^8.0.1 || ^7.2.5" from react-konva@18.2.5
npm ERR! node_modules/react-konva
npm ERR!   react-konva@"^18.2.5" from the root project
npm ERR!   react-konva@"^18.0.0-0" from react-konva-utils@1.0.0
npm ERR!   node_modules/react-konva-utils
npm ERR!     react-konva-utils@"1.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: konva@8.4.3
npm ERR! node_modules/konva
npm ERR!   peer konva@"^8.0.1 || ^7.2.5" from react-konva@18.2.5
npm ERR!   node_modules/react-konva
npm ERR!     react-konva@"^18.2.5" from the root project
npm ERR!     react-konva@"^18.0.0-0" from react-konva-utils@1.0.0
npm ERR!     node_modules/react-konva-utils
npm ERR!       react-konva-utils@"1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/paul/.npm/_logs/2023-04-14T18_36_49_438Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2023-04-14T18_36_49_438Z-debug-0.log
```
