### ISSUE TITLE
No Storybook config file

### ISSUE THREAD

**Issue by miker2049** [konvajs/react-konva-utils#30]
It doesn't seem like the necessary config files are checked in to allow viewing stories.  

I get this running `npm run storybook`

```sh
ERR! Error: No configuration files have been found in your configDir (/home/mik/react-konva-utils/.storybook).
ERR! Storybook needs either a "main" or "config" file.
ERR!     at validateConfigurationFiles (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js:50:11)
ERR!     at loadCustomPresets (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js:19:62)
ERR!     at loadAllPresets (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/presets.js:357:131)
ERR!     at buildDevStandalone (/home/mik/react-konva-utils/node_modules/@storybook/core-server/dist/cjs/build-dev.js:108:48)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async buildDev (/home/mik/react-konva-utils/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  Error: No configuration files have been found in your configDir (/home/mik/react-konva-utils/.storybook).
ERR! Storybook needs either a "main" or "config" file.
ERR!     at validateConfigurationFiles (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js:50:11)
ERR!     at loadCustomPresets (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js:19:62)
ERR!     at loadAllPresets (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/presets.js:357:131)
ERR!     at buildDevStandalone (/home/mik/react-konva-utils/node_modules/@storybook/core-server/dist/cjs/build-dev.js:108:48)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async buildDev (/home/mik/react-konva-utils/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js:50
    throw new Error((0, _tsDedent.default)`
          ^

Error: No configuration files have been found in your configDir (/home/mik/react-konva-utils/.storybook).
Storybook needs either a "main" or "config" file.
    at validateConfigurationFiles (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js:50:11)
    at loadCustomPresets (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js:19:62)
    at loadAllPresets (/home/mik/react-konva-utils/node_modules/@storybook/core-common/dist/cjs/presets.js:357:131)
    at buildDev (/home/mik/react-konva-utils/node_modules/@storybook/core-server/dist/cjs/build-dev.js:209:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.1
```

**Comment by lavrton** [comment]
I am not certain why you have this. It is running just fine for me. I tried with node v16.

**Comment by lavrton** [comment]
Added.
